services:
  - type: web
    name: paiement-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn paiement_project.wsgi:application"
    envVars:
      - fromFile: .env